import { Vendor } from "../types/vendor";

export const vendors: Vendor[] = [
  {
    id: "1",

    name: "Elegant Catering",
    category: "Catering",
    location: "Eastbridge",
    verified: true,
    price: "$1,300",
    rating: 4.8,
    reviewCount: 34,
    description: "Premium catering services for all occasions",
    images: [
      "/images/catering-1.jpg",
      "/images/catering-2.jpg",
      "/images/catering-3.jpg",
      "/images/catering-4.jpg",
    ],
    services: ["Full-service catering", "Custom menus", "Event staffing"],
    companyName: "Elegant Catering Services",
    businessNumber: "BN: 12345678",
    storeAddress: "123 Food Street, Eastbridge",
    storeLocation: "123 Food Street, Eastbridge",
    verifiedDate: "07/02/2022",
    reviews: [
      {
        id: "1",
        userName: "Adam Sandler",
        userAvatar: "/avatars/adam.jpg",
        comment:
          "It was a great service and overall experience working with them.",
        date: "2022-11-28",
        likes: 12,
        rating: 4.5,
        content: "The food was delicious and the service was impeccable!",
        isLiked: false,
        currentLikes: 12,
      },
    ],
  },
  {
    id: "2",
    name: "Aubrey Halls",
    category: "Venue",
    location: "Eastbridge",
    verified: true,
    price: "$2,500",
    rating: 4.99,
    reviewCount: 21,
    description:
      "Find the perfect space for your event. Our venues offer flexible layouts, premium amenities, and full-service support to accommodate any occasion.",
    images: [
      "/images/venue-1.jpg",
      "/images/venue-2.jpg",
      "/images/venue-3.jpg",
      "/images/venue-4.jpg",
    ],
    services: ["Wedding venues", "Corporate events", "Party spaces"],
    companyName: "Theresa Webb Halls",
    businessNumber: "BN: 28913480",
    storeAddress: "123 Broadway Avenue, NY 10001",
    storeLocation: "Grand Maple Theatre, New York City",
    verifiedDate: "07/02/2022",
    reviews: [
      {
        id: "2",
        userName: "Sarah Connor",
        userAvatar: "/avatars/sarah.jpg",
        comment: "Beautiful venue with excellent service!",
        date: "2022-10-15",
        likes: 8,
        rating: 5,
        content: "The venue was stunning and the staff were very helpful.",
        isLiked: false,
        currentLikes: 8,
      },
    ],
  },
  {
    id: "3",

    name: "Melody Makers Band",
    category: "Entertainment",
    location: "Westridge",
    verified: true,
    price: "$8,000",
    rating: 4.6,
    reviewCount: 18,
    description: "Live band for weddings, parties, and corporate functions.",
    images: [
      "/images/band-1.jpg",
      "/images/band-2.jpg",
      "/images/band-3.jpg",
      "/images/band-4.jpg",
    ],
    services: ["Live band", "DJ services", "MC services"],
    companyName: "Melody Makers LLC",
    businessNumber: "BN: 56781234",
    storeAddress: "101 Music Lane, Brooklyn",
    storeLocation: "101 Music Lane, Brooklyn",
    verifiedDate: "08/15/2023",
    reviews: [
      {
        id: "3",
        userName: "John Doe",
        userAvatar: "/avatars/john.jpg",
        comment: "Amazing band! They made our wedding unforgettable.",
        date: "2022-09-10",
        likes: 15,
        rating: 5,
        content:
          "The band was amazing and the music was perfect for our event.",
          isLiked: false,
          currentLikes: 15,
      },
    ],
  },
  {
    id: "4",

    name: "SnapFlash Photography",
    category: "Photography",
    location: "Westridge",
    verified: false,
    price: "$2,200",
    rating: 4.5,
    reviewCount: 44,
    description: "Capturing timeless moments with professional flair.",
    images: [
      "/images/photo-1.jpg",
      "/images/photo-2.jpg",
      "/images/photo-3.jpg",
      "/images/photo-4.jpg",
    ],
    services: ["Event photography", "Photo editing", "Prints and albums"],
    companyName: "SnapFlash Studios",
    businessNumber: "BN: 90871234",
    storeAddress: "123 Photo Lane, New York City",
    storeLocation: "9th Avenue, Manhattan",
    verifiedDate: "N/A",
    reviews: [
      {
        id: "4",
        userName: "Jessica Lee",
        userAvatar: "/avatars/jessica.jpg",
        comment: "Professional and creative team, loved the photos!",
        date: "2022-08-21",
        likes: 10,
        rating: 5,
        content: "The photos were stunning and the team was very professional.",
        isLiked: false,
        currentLikes: 10,
      },
    ],
  },
  {
    id: "5",
    name: "Flora & Fern",
    category: "EventDecor",
    location: "Chicago",
    verified: true,
    price: "$1,550",
    rating: 4.9,
    reviewCount: 52,
    description: "Bespoke event floral design and venue decoration.",
    images: [
      "/images/decor-1.jpg",
      "/images/decor-2.jpg",
      "/images/decor-3.jpg",
      "/images/decor-4.jpg",
    ],
    services: ["Floral design", "Table setup", "Custom décor themes"],
    companyName: "Flora & Fern Decor",
    storeAddress: "456 Bloom Blvd, Chicago",
    businessNumber: "BN: 22334455",
    storeLocation: "456 Bloom Blvd, Chicago",
    verifiedDate: "06/10/2023",
    reviews: [
      {
        id: "5",
        userName: "Emily Carter",
        userAvatar: "/avatars/emily.jpg",
        comment:
          "Stunning floral arrangements and beautiful decor for our event.",
        date: "2022-07-19",
        likes: 17,
        rating: 5,
        content:
          "The floral arrangements were stunning and the decor was perfect.",
          isLiked: false,
          currentLikes: 17,
      },
    ],
  },
  {
    id: "6",
    name: "Tasty Treats Bakery",
    category: "Catering",
    location: "Westridge",
    verified: false,
    price: "$5,000",
    rating: 4.3,
    reviewCount: 29,
    description:
      "Delicious cakes, cupcakes, and pastries for every celebration.",
    images: [
      "/images/bakery-1.jpg",
      "/images/bakery-2.jpg",
      "/images/bakery-3.jpg",
      "/images/bakery-4.jpg",
    ],
    services: ["Custom cakes", "Dessert tables", "Pastry trays"],
    companyName: "Tasty Treats Inc.",
    businessNumber: "BN: 33445566",
    storeLocation: "Sweet Street, Queens",
    storeAddress: "88 Sweet Street, Queens",
    verifiedDate: "N/A",
    reviews: [
      {
        id: "6",
        userName: "Liam Johnson",
        userAvatar: "/avatars/liam.jpg",
        comment: "The cake was delicious and beautifully decorated!",
        date: "2022-06-30",
        likes: 12,
        rating: 5,
        content: "The cake was delicious and beautifully decorated!",
        isLiked: false,
        currentLikes: 12,
      },
    ],
  },
  {
    id: "7",
    name: "Bella Bride Styling",
    category: "Westridge",
    location: "Los Angeles",
    verified: true,
    price: "$3,500",
    rating: 5.0,
    reviewCount: 11,
    description:
      "Bridal styling, gowns, and accessories with a personal touch.",
    images: [
      "/images/fashion-1.jpg",
      "/images/fashion-2.jpg",
      "/images/fashion-3.jpg",
      "/images/fashion-4.jpg",
    ],
    services: ["Bridal gowns", "Makeup & styling", "Fitting sessions"],
    companyName: "Bella Bride Fashion House",
    businessNumber: "BN: 77889900",
    storeAddress: "123 Bridal Lane, Los Angeles",
    storeLocation: "Sunset Blvd, Los Angeles",
    verifiedDate: "01/12/2024",
    reviews: [
      {
        id: "7",
        userName: "Sophia Turner",
        userAvatar: "/avatars/sophia.jpg",
        comment: "Absolutely loved the bridal styling and attention to detail!",
        date: "2023-04-10",
        likes: 13,
        rating: 5,
        content: "Absolutely loved the bridal styling and attention to detail!",
        isLiked: false,
        currentLikes: 13,
      },
    ],
  },
  {
    id: "8",

    name: "Party Pal Rentals",
    category: "Logistics",
    location: "Southbridge",
    verified: true,
    price: "$7,505",
    rating: 4.4,
    reviewCount: 37,
    description: "Rent everything you need to make your party a blast!",
    images: [
      "/images/rentals-1.jpg",
      "/images/rentals-2.jpg",
      "/images/rentals-3.jpg",
      "/images/rentals-4.jpg",
    ],
    services: [
      "Chair/table rentals",
      "Tents & inflatables",
      "Lighting & sound",
    ],
    companyName: "Party Pal Inc.",
    businessNumber: "BN: 11122233",
    storeAddress: "789 Party Lane, Southbridge",
    storeLocation: "22 Fun Lane, Newark",
    verifiedDate: "10/20/2023",
    reviews: [
      {
        id: "8",
        userName: "Daniel Evans",
        userAvatar: "/avatars/daniel.jpg",
        comment: "Great selection of party rentals and fast delivery!",
        date: "2023-03-22",
        likes: 11,
        rating: 2.3,
        content: "Great selection of party rentals and fast delivery!",
        isLiked: false,
        currentLikes: 11,
      },
    ],
  },
  {
    id: "9",
    name: "Golden Hour Films",
    category: "Photography",
    location: "Southbridge",
    verified: true,
    price: "From $3,500",
    rating: 4.7,
    reviewCount: 25,
    description: "Cinematic wedding and event videography packages.",
    images: [
      "/images/video-1.jpg",
      "/images/video-2.jpg",
      "/images/video-3.jpg",
      "/images/video-4.jpg",
    ],
    services: ["Highlight reels", "Drone coverage", "Full event edits"],
    companyName: "Golden Hour Studios",
    storeAddress: "456 Film Street, Atlanta",
    businessNumber: "BN: 55667788",
    storeLocation: "Peachtree Ave, Atlanta",
    verifiedDate: "03/08/2023",
    reviews: [
      {
        id: "9",
        userName: "Olivia Brown",
        userAvatar: "/avatars/olivia.jpg",
        comment: "The video captured our day perfectly, highly recommend!",
        date: "2023-02-14",
        likes: 18,
        rating: 4.7,
        content: "The video captured our day perfectly, highly recommend!",
        isLiked: false,
        currentLikes: 18,
      },
    ],
  },
  {
    id: "10",

    name: "Sparkle Cleaning Crew",
    category: "AudioVisual",
    location: "Southbridge",
    verified: false,
    price: "$1,020",
    rating: 4.2,
    reviewCount: 15,
    description: "Post-event cleanup with professional service and smiles.",
    images: [
      "/images/cleaning-1.jpg",
      "/images/cleaning-2.jpg",
      "/images/cleaning-3.jpg",
      "/images/cleaning-4.jpg",
    ],
    services: ["Post-party cleanup", "Venue sanitation", "Trash disposal"],
    companyName: "Sparkle Cleaning Crew",
    storeAddress: "789 Clean Street, Dallas",
    businessNumber: "BN: 44556677",
    storeLocation: "Cedar Street, Dallas",
    verifiedDate: "N/A",
    reviews: [
      {
        id: "10",
        userName: "Henry Clark",
        userAvatar: "/avatars/henry.jpg",
        comment: "The cleaning crew was efficient and left the venue spotless!",
        date: "2023-01-05",
        likes: 7,
        rating: 1.2,
        content: "The cleaning crew was efficient and left the venue spotless!",
        isLiked: false,
        currentLikes: 7,
      },
    ],
  },
  {
    id: "11",
    name: "DJ Sonic Beats",
    category: "Entertainment",
    location: "Central District",
    verified: true,
    price: "$1,250",
    rating: 4.85,
    reviewCount: 40,
    description:
      "Professional DJ services to keep your guests dancing all night.",
    images: [
      "/images/dj-1.jpg",
      "/images/dj-2.jpg",
      "/images/dj-3.jpg",
      "/images/dj-4.jpg",
    ],
    services: ["Live DJ", "Lighting effects", "Custom playlists"],
    companyName: "Sonic Beats Entertainment",
    businessNumber: "BN: 99887766",
    storeAddress: "45 Music Row, Houston",
    storeLocation: "45 Music Row, Houston",
    verifiedDate: "04/30/2022",
    reviews: [
      {
        id: "11",
        userName: "Jason Lee",
        userAvatar: "/avatars/jason.jpg",
        comment: "The DJ kept the party going all night, fantastic energy!",
        date: "2023-06-18",
        likes: 22,
        rating: 4.9,
        content: "The DJ kept the party going all night, fantastic energy!",
        isLiked: false,
        currentLikes: 22,
      },
    ],
  },
  {
    id: "12",
    name: "Moments By Mara",
    category: "Catering",
    location: "Northbridge",
    verified: true,
    price: "$1,880",
    rating: 4.95,
    reviewCount: 39,
    description:
      "Candid and creative event photography to preserve your memories.",
    images: [
      "/images/photo2-1.jpg",
      "/images/photo2-2.jpg",
      "/images/photo2-3.jpg",
      "/images/photo2-4.jpg",
    ],
    services: ["Weddings", "Portrait sessions", "Event coverage"],
    companyName: "Moments By Mara Co.",
    storeAddress: "123 Event Lane, San Diego",
    businessNumber: "BN: 66778899",
    storeLocation: "Ocean Avenue, San Diego",
    verifiedDate: "11/18/2023",
    reviews: [
      {
        id: "12",
        userName: "Mara Jennings",
        userAvatar: "/avatars/mara.jpg",
        comment: "Captured our special day perfectly, highly recommended!",
        date: "2023-05-12",
        likes: 19,
        rating: 4.8,
        content: "Captured our special day perfectly, highly recommended!",
        isLiked: false,
        currentLikes: 19,
      },
    ],
  },

  {
    id: "14",
    name: "Golden Fork Catering",
    category: "Catering",
    location: "Central District",
    verified: true,
    price: "$3,000",
    rating: 4.75,
    reviewCount: 48,
    description:
      "Exquisite menus for weddings, corporate functions, and luxury events. Our chefs bring global flavors to your plate.",
    images: [
      "/images/catering-1.jpg",
      "/images/catering-2.jpg",
      "/images/catering-3.jpg",
    ],
    services: ["Buffet setups", "Cocktail service", "Custom menus"],
    companyName: "Golden Fork Co.",
    businessNumber: "BN: 99887766",
    storeAddress: "45 Savory Lane, Brooklyn",
    storeLocation: "45 Savory Lane, Brooklyn",
    verifiedDate: "09/04/2023",
    reviews: [
      {
        id: "14",
        userName: "Linda Green",
        userAvatar: "/avatars/linda.jpg",
        comment: "The food was delicious and the service was impeccable!",
        date: "2023-07-21",
        likes: 20,
        rating: 4.9,
        content: "The food was delicious and the service was impeccable!",
        isLiked: false,
        currentLikes: 20,
      },
    ],
  },
  {
    id: "15",
    name: "DJ Soundwave",
    category: "Catering",
    location: "Central District",
    verified: true,
    price: "$6,000",
    rating: 4.9,
    reviewCount: 62,
    description:
      "Electrifying DJ services with curated playlists, top-tier equipment, and vibes that keep guests dancing all night.",
    images: ["/images/dj-1.jpg", "/images/dj-2.jpg"],
    services: ["Weddings", "Corporate parties", "Birthday bashes"],
    companyName: "Soundwave Entertainment",
    storeAddress: "123 Music Lane, New York City",
    businessNumber: "BN: 11223344",
    storeLocation: "Central Beats Studio, Manhattan",
    verifiedDate: "02/12/2024",
    reviews: [
      {
        id: "15",
        userName: "Chris Martin",
        userAvatar: "/avatars/chris.jpg",
        comment: "The DJ was incredible and kept the energy high all night!",
        date: "2023-08-15",
        likes: 25,
        rating: 4.95,
        content: "The DJ was incredible and kept the energy high all night!",
        isLiked: false,
        currentLikes: 25,
      },
    ],
  },
  {
    id: "16",

    name: "Flora Luxe Designs",
    category: "Catering",
    location: "Central District",
    verified: true,
    price: "$2,550",
    rating: 4.65,
    reviewCount: 37,
    description:
      "Artfully crafted floral arrangements and décor packages for events of all styles — rustic, modern, romantic, and more.",
    images: [
      "/images/decor-1.jpg",
      "/images/decor-2.jpg",
      "/images/decor-3.jpg",
    ],
    services: ["Floral design", "Venue styling", "Custom themes"],
    companyName: "Flora Luxe Co.",
    businessNumber: "BN: 44556677",
    storeLocation: "Bloom Alley, Bronx",
    storeAddress: "Bloom Alley, Bronx",
    verifiedDate: "05/22/2023",
    reviews: [
      {
        id: "16",
        userName: "Grace Kim",
        userAvatar: "/avatars/grace.jpg",
        comment:
          "The floral arrangements were breathtaking and made our event truly special.",
        date: "2023-09-10",
        likes: 16,
        rating: 4.8,
        content:
          "The floral arrangements were breathtaking and made our event truly special.",
          isLiked: false,
          currentLikes: 16,
      },
    ],
  },
];

export function getVendorById(id: string): Vendor | undefined {
  return vendors.find((vendor) => vendor.id === id);
}
