import { Vendor } from "../types/vendor";

export const vendors: Vendor[] = [
  {
    id: "1",
    name: "Elegant Catering",
    category: "Catering",
    location: "Eastbridge",
    verified: true,
    price: "From $100",
    rating: 4.8,
    reviewCount: 34,
    description: "Premium catering services for all occasions",
    images: [
      "/images/catering-1.jpg",
      "/images/catering-2.jpg",
      "/images/catering-3.jpg",
      "/images/catering-4.jpg",
    ],
    services: ["Full-service catering", "Custom menus", "Event staffing"],
    companyName: "Elegant Catering Services",
    businessNumber: "BN: 12345678",
    storeLocation: "123 Food Street, Eastbridge",
    verifiedDate: "07/02/2022",
  },
  {
    id: "2",
    name: "Aubrey Halls",
    category: "Venue",
    location: "Eastbridge",
    verified: true,
    price: "From $500",
    rating: 4.99,
    reviewCount: 21,
    description:
      "Find the perfect space for your event. Our venues offer flexible layouts, premium amenities, and full-service support to accommodate any occasion.",
    images: [
      "/images/venue-1.jpg",
      "/images/venue-2.jpg",
      "/images/venue-3.jpg",
      "/images/venue-4.jpg",
    ],
    services: ["Wedding venues", "Corporate events", "Party spaces"],
    companyName: "Theresa Webb Halls",
    businessNumber: "BN: 28913480",
    storeLocation: "Grand Maple Theatre, New York City",
    verifiedDate: "07/02/2022",
  },
  {
    id: "3",
    name: "Melody Makers Band",
    category: "Entertainment",
    location: "Brooklyn",
    verified: true,
    price: "From $800",
    rating: 4.6,
    reviewCount: 18,
    description: "Live band for weddings, parties, and corporate functions.",
    images: [
      "/images/band-1.jpg",
      "/images/band-2.jpg",
      "/images/band-3.jpg",
      "/images/band-4.jpg",
    ],
    services: ["Live band", "DJ services", "MC services"],
    companyName: "Melody Makers LLC",
    businessNumber: "BN: 56781234",
    storeLocation: "101 Music Lane, Brooklyn",
    verifiedDate: "08/15/2023",
  },
  {
    id: "4",
    name: "SnapFlash Photography",
    category: "Photography",
    location: "Manhattan",
    verified: false,
    price: "From $200",
    rating: 4.5,
    reviewCount: 44,
    description: "Capturing timeless moments with professional flair.",
    images: [
      "/images/photo-1.jpg",
      "/images/photo-2.jpg",
      "/images/photo-3.jpg",
      "/images/photo-4.jpg",
    ],
    services: ["Event photography", "Photo editing", "Prints and albums"],
    companyName: "SnapFlash Studios",
    businessNumber: "BN: 90871234",
    storeLocation: "9th Avenue, Manhattan",
    verifiedDate: "N/A",
  },
  {
    id: "5",
    name: "Flora & Fern",
    category: "EventDecor",
    location: "Chicago",
    verified: true,
    price: "From $150",
    rating: 4.9,
    reviewCount: 52,
    description: "Bespoke event floral design and venue decoration.",
    images: [
      "/images/decor-1.jpg",
      "/images/decor-2.jpg",
      "/images/decor-3.jpg",
      "/images/decor-4.jpg",
    ],
    services: ["Floral design", "Table setup", "Custom décor themes"],
    companyName: "Flora & Fern Decor",
    businessNumber: "BN: 22334455",
    storeLocation: "456 Bloom Blvd, Chicago",
    verifiedDate: "06/10/2023",
  },
  {
    id: "6",
    name: "Tasty Treats Bakery",
    category: "Catering",
    location: "Queens",
    verified: false,
    price: "From $50",
    rating: 4.3,
    reviewCount: 29,
    description:
      "Delicious cakes, cupcakes, and pastries for every celebration.",
    images: [
      "/images/bakery-1.jpg",
      "/images/bakery-2.jpg",
      "/images/bakery-3.jpg",
      "/images/bakery-4.jpg",
    ],
    services: ["Custom cakes", "Dessert tables", "Pastry trays"],
    companyName: "Tasty Treats Inc.",
    businessNumber: "BN: 33445566",
    storeLocation: "88 Sweet Street, Queens",
    verifiedDate: "N/A",
  },
  {
    id: "7",
    name: "Bella Bride Styling",
    category: "Logistics",
    location: "Los Angeles",
    verified: true,
    price: "From $300",
    rating: 5.0,
    reviewCount: 11,
    description:
      "Bridal styling, gowns, and accessories with a personal touch.",
    images: [
      "/images/fashion-1.jpg",
      "/images/fashion-2.jpg",
      "/images/fashion-3.jpg",
      "/images/fashion-4.jpg",
    ],
    services: ["Bridal gowns", "Makeup & styling", "Fitting sessions"],
    companyName: "Bella Bride Fashion House",
    businessNumber: "BN: 77889900",
    storeLocation: "Sunset Blvd, Los Angeles",
    verifiedDate: "01/12/2024",
  },
  {
    id: "8",
    name: "Party Pal Rentals",
    category: "Logistics",
    location: "New Jersey",
    verified: true,
    price: "From $75",
    rating: 4.4,
    reviewCount: 37,
    description: "Rent everything you need to make your party a blast!",
    images: [
      "/images/rentals-1.jpg",
      "/images/rentals-2.jpg",
      "/images/rentals-3.jpg",
      "/images/rentals-4.jpg",
    ],
    services: [
      "Chair/table rentals",
      "Tents & inflatables",
      "Lighting & sound",
    ],
    companyName: "Party Pal Inc.",
    businessNumber: "BN: 11122233",
    storeLocation: "22 Fun Lane, Newark",
    verifiedDate: "10/20/2023",
  },
  {
    id: "9",
    name: "Golden Hour Films",
    category: "Photography",
    location: "Atlanta",
    verified: true,
    price: "From $350",
    rating: 4.7,
    reviewCount: 25,
    description: "Cinematic wedding and event videography packages.",
    images: [
      "/images/video-1.jpg",
      "/images/video-2.jpg",
      "/images/video-3.jpg",
      "/images/video-4.jpg",
    ],
    services: ["Highlight reels", "Drone coverage", "Full event edits"],
    companyName: "Golden Hour Studios",
    businessNumber: "BN: 55667788",
    storeLocation: "Peachtree Ave, Atlanta",
    verifiedDate: "03/08/2023",
  },
  {
    id: "10",
    name: "Sparkle Cleaning Crew",
    category: "AudioVisual",
    location: "Dallas",
    verified: false,
    price: "From $120",
    rating: 4.2,
    reviewCount: 15,
    description: "Post-event cleanup with professional service and smiles.",
    images: [
      "/images/cleaning-1.jpg",
      "/images/cleaning-2.jpg",
      "/images/cleaning-3.jpg",
      "/images/cleaning-4.jpg",
    ],
    services: ["Post-party cleanup", "Venue sanitation", "Trash disposal"],
    companyName: "Sparkle Cleaning Crew",
    businessNumber: "BN: 44556677",
    storeLocation: "Cedar Street, Dallas",
    verifiedDate: "N/A",
  },
  {
    id: "11",
    name: "DJ Sonic Beats",
    category: "Entertainment",
    location: "Houston",
    verified: true,
    price: "From $250",
    rating: 4.85,
    reviewCount: 40,
    description:
      "Professional DJ services to keep your guests dancing all night.",
    images: [
      "/images/dj-1.jpg",
      "/images/dj-2.jpg",
      "/images/dj-3.jpg",
      "/images/dj-4.jpg",
    ],
    services: ["Live DJ", "Lighting effects", "Custom playlists"],
    companyName: "Sonic Beats Entertainment",
    businessNumber: "BN: 99887766",
    storeLocation: "45 Music Row, Houston",
    verifiedDate: "04/30/2022",
  },
  {
    id: "12",
    name: "Moments By Mara",
    category: "Catering",
    location: "San Diego",
    verified: true,
    price: "From $180",
    rating: 4.95,
    reviewCount: 39,
    description:
      "Candid and creative event photography to preserve your memories.",
    images: [
      "/images/photo2-1.jpg",
      "/images/photo2-2.jpg",
      "/images/photo2-3.jpg",
      "/images/photo2-4.jpg",
    ],
    services: ["Weddings", "Portrait sessions", "Event coverage"],
    companyName: "Moments By Mara Co.",
    businessNumber: "BN: 66778899",
    storeLocation: "Ocean Avenue, San Diego",
    verifiedDate: "11/18/2023",
  },

  {
    id: "14",
    name: "Golden Fork Catering",
    category: "Catering",
    location: "Brooklyn",
    verified: true,
    price: "From $300",
    rating: 4.75,
    reviewCount: 48,
    description:
      "Exquisite menus for weddings, corporate functions, and luxury events. Our chefs bring global flavors to your plate.",
    images: [
      "/images/catering-1.jpg",
      "/images/catering-2.jpg",
      "/images/catering-3.jpg",
    ],
    services: ["Buffet setups", "Cocktail service", "Custom menus"],
    companyName: "Golden Fork Co.",
    businessNumber: "BN: 99887766",
    storeLocation: "45 Savory Lane, Brooklyn",
    verifiedDate: "09/04/2023",
  },
  {
    id: "15",
    name: "DJ Soundwave",
    category: "Catering",
    location: "Manhattan",
    verified: true,
    price: "From $600",
    rating: 4.9,
    reviewCount: 62,
    description:
      "Electrifying DJ services with curated playlists, top-tier equipment, and vibes that keep guests dancing all night.",
    images: ["/images/dj-1.jpg", "/images/dj-2.jpg"],
    services: ["Weddings", "Corporate parties", "Birthday bashes"],
    companyName: "Soundwave Entertainment",
    businessNumber: "BN: 11223344",
    storeLocation: "Central Beats Studio, Manhattan",
    verifiedDate: "02/12/2024",
  },
  {
    id: "16",
    name: "Flora Luxe Designs",
    category: "Catering",
    location: "Bronx",
    verified: true,
    price: "From $250",
    rating: 4.65,
    reviewCount: 37,
    description:
      "Artfully crafted floral arrangements and décor packages for events of all styles — rustic, modern, romantic, and more.",
    images: [
      "/images/decor-1.jpg",
      "/images/decor-2.jpg",
      "/images/decor-3.jpg",
    ],
    services: ["Floral design", "Venue styling", "Custom themes"],
    companyName: "Flora Luxe Co.",
    businessNumber: "BN: 44556677",
    storeLocation: "Bloom Alley, Bronx",
    verifiedDate: "05/22/2023",
  },
];

export function getVendorById(id: string): Vendor | undefined {
  return vendors.find((vendor) => vendor.id === id);
}
